### ISSUE TITLE
can't compile on FreeBSD 14.1/14.2

### ISSUE THREAD

**Issue by yjqg6666** [wulf7/linux-libbsd#2]
Compiling on FreeBSD 14.2 got the following error.
> linux_libbsd.c:38:10: fatal error: 'compat/linux/linux_sysproto.h' file not found
>    38 | #include <compat/linux/linux_sysproto.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 1 error generated.
> *** Error code 1

The error would also be expected on FreeBSD 14.1. The freebsd-src/sys/compat/linux/linux_sysproto.h has been removed from tree since FreeBSD 14.1.

The related commits/reviews are [D41976](https://reviews.freebsd.org/D41976) and [D41901](https://reviews.freebsd.org/D41901) .

**Comment by wulf7** [comment]
Test latest master branch

**Comment by yjqg6666** [comment]
It works now.
